# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.questaInstallPath C:/questasim64_10.6c/win64
create_project -in_memory -part xcku060-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Trigger_class_record/buffer_fifo.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/GBT/gbt_bank/xilinx_ku/xlx_ku_gbt_bank_package.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/GBT/gbt_bank/core_sources/gbt_bank_package.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/GBT/gbt_bank/core_sources/gbt_bank_package_itsmft.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/GBT/example_designs/core_sources/exampleDsgn_package.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/GBT/example_designs/core_sources/exampleDsgn_package_itsmft.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Interaction_record_zerosuppr/ir_statemachine.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Trigger_class_record/packer.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Interaction_record_zerosuppr/packer_ir2.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Trigger_class_record/prsg_tcr.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Trigger_class_record/tc_statemachine.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Interaction_record_zerosuppr/top_ir_statemachine.vhd}
  {C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Trigger_class_record/top_tc_statemachine.vhd}
}
read_vhdl -vhdl2008 -library xil_defaultlib {{C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/imports/alice/IRandTCR/ctpreadout.vhd}}
read_ip -quiet {{C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt_ooc.xdc}}]

read_ip -quiet {{C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/tc_fifo/tc_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/tc_fifo/tc_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/tc_fifo/tc_fifo_ooc.xdc}}]

read_ip -quiet {{C:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/ir_fifo/ir_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/ir_fifo/ir_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Simone Ragoni/alice/IRandTCR/ctpreadout.srcs/sources_1/ip/ir_fifo/ir_fifo_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ctpreadout -part xcku060-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ctpreadout.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ctpreadout_utilization_synth.rpt -pb ctpreadout_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
