# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dc_fifo_gbt2olt/dc_fifo_gbt2olt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dc_fifo_gbt2olt || ORIG_REF_NAME==dc_fifo_gbt2olt} -quiet] -quiet
