######################################################################
#
# File name : IR_tb.udo
# Created on: Tue Feb 08 09:09:59 +0100 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
