######################################################################
#
# File name : IR_tb_wave.do
# Created on: Tue Feb 08 09:09:59 +0100 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
