######################################################################
#
# File name : IR_tb_compile.do
# Created on: Fri Feb 11 15:56:58 +0100 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.6c\\win64\\vlib questa_lib/work
C:\\questasim64_10.6c\\win64\\vlib questa_lib/msim

C:\\questasim64_10.6c\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.6c\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.6c\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../ctpreadout2.ip_user_files/ip/ir_fifo/sim/ir_fifo.v" \

C:\\questasim64_10.6c\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../../Trigger_class_record/buffer_fifo.vhd" \
"../../../../../Interaction_record_zerosuppr/ir_statemachine.vhd" \
"../../../../../Interaction_record_zerosuppr/packer_ir2.vhd" \
"../../../../../Trigger_class_record/prsg_tcr.vhd" \
"../../../../../Interaction_record_zerosuppr/top_ir_statemachine.vhd" \
"../../../../../IR_tb.vhd" \

# compile glbl module
C:\\questasim64_10.6c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

