######################################################################
#
# File name : tcr_tb_wave.do
# Created on: Fri Feb 11 21:14:40 +0100 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
