######################################################################
#
# File name : tcr_tb_simulate.do
# Created on: Fri Feb 11 21:14:40 +0100 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib tcr_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tcr_tb_wave.do}

view wave
view structure
view signals

do {tcr_tb.udo}

run 1000ns
