######################################################################
#
# File name : IR_tb.udo
# Created on: Wed Feb 02 08:47:50 +0100 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
