######################################################################
#
# File name : IR_tb_compile.do
# Created on: Wed Feb 02 09:06:50 +0100 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.6c\\win64\\vlib questa_lib/work
C:\\questasim64_10.6c\\win64\\vlib questa_lib/msim

C:\\questasim64_10.6c\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.6c\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.6c\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../ctpreadout.ip_user_files/ip/ir_fifo/sim/ir_fifo.v" \

C:\\questasim64_10.6c\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Trigger_class_record/buffer_fifo.vhd" \
"../../../../ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Interaction_record_zerosuppr/ir_statemachine.vhd" \
"../../../../ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Interaction_record_zerosuppr/packer_ir2.vhd" \
"../../../../ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Trigger_class_record/prsg_tcr.vhd" \
"../../../../ctpreadout.srcs/sources_1/imports/alice/IRandTCR/Interaction_record_zerosuppr/top_ir_statemachine.vhd" \
"../../../../ctpreadout.srcs/sim_1/imports/IRandTCR/IR_tb.vhd" \

# compile glbl module
C:\\questasim64_10.6c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

