######################################################################
#
# File name : tcr_tb.udo
# Created on: Wed Feb 02 09:04:17 +0100 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
